services:
  - type: web
    name: ai-equity-research
    env: python
    buildCommand: |
      pip install --upgrade pip
      pip install -r requirements.txt
    startCommand: |
      python main.py
    plan: starter
    healthCheckPath: /health
    envVars:
      - key: ENVIRONMENT
        value: production
      - key: PORT
        value: 8000
      - key: WORKERS
        value: 1
      - key: PYTHONPATH
        value: /opt/render/project/src
      - key: OPENAI_KEY
        sync: false
      - key: CLAUDE_KEY
        sync: false
      - key: GROK_KEY
        sync: false
      - key: GEMINI_KEY
        sync: false
      - key: PERPLEXITY_KEY
        sync: false
      - key: ALPHA_VANTAGE_KEY
        sync: false
      - key: FRED_KEY
        sync: false
      - key: NEWS_API_KEY
        sync: false
      - key: POLYGON_KEY
        sync: false
      - key: NASDAQ_KEY
        sync: false
      - key: REDDIT_CLIENT_ID
        sync: false
      - key: REDDIT_CLIENT_SECRET
        sync: false
      - key: TWITTER_BEARER_TOKEN
        sync: false
    disk:
      name: ai-equity-data
      mountPath: /opt/render/project/src/data
      sizeGB: 1

  - type: worker
    name: ai-equity-worker
    env: python
    buildCommand: |
      pip install --upgrade pip
      pip install -r requirements.txt
    startCommand: |
      python -c "
from enhanced_equity_system import APIConfig, get_research_system
import schedule, time, asyncio
async def update():
    sys = get_research_system()
    await sys.build_sector_rotation_table(days=30)
schedule.every(5).minutes.do(lambda: asyncio.run(update()))
while True:
    schedule.run_pending()
    time.sleep(1)
"
    plan: starter
    envVars:
      - key: ENVIRONMENT
        value: production
      - key: OPENAI_KEY
        sync: false
      - key: FRED_KEY
        sync: false
      - key: ALPHA_VANTAGE_KEY
        sync: false
      - key: NEWS_API_KEY
        sync: false

  - type: redis
    name: ai-equity-cache
    plan: starter
    maxmemoryPolicy: allkeys-lru

static:
  - publicPath: /static
    dir: static
  - publicPath: /templates
    dir: templates

healthCheck:
  path: /health
  interval: 30s
  timeout: 10s
  failureThreshold: 3
  successThreshold: 1
